version: 0.2
phases:
  install:
    runtime-versions:
        python: python3.6
  build:
    commands:
      - export BUCKET=za-wild-poc
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml